### ISSUE TITLE
Not working on Debian bases

### ISSUE THREAD

**Issue by anjanik012** [anjanik012/suto#6]
For some reason, the module is not called by the system. The compilation is working but is not being called. The module, as it is, is working on Arch Linux bases. 

Maybe on Debian bases, the module is not linked properly.
@shaileshaanand

**Comment by shaileshaanand** [comment]
After placing every .cpp and .h file under the same directory run
```
g++ -fPIC -fno-stack-protector -shared *.cpp -o libpam_suto.so -l pthread -l boost_log -l boost_system -l boost_thread -l boost_random -l crypt -DBOOST_LOG_DYN_LINK
```
the generated (libpam_suto.so) file works on `ubuntu 20.04`

**Comment by anjanik012** [comment]
Something is wrong with our linking with cmake.

**Comment by anjanik012** [comment]
I'll try it on fedora 33

**Comment by shaileshaanand** [comment]
Place every `.cpp` and `.h` file in a folder and run (This generates `pam.so`):
```
mkdir manbuild
g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK suto_pam.cpp -o manbuild/suto_pam.cpp.o
g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK authenticator.cpp -o manbuild/authenticator.cpp.o
g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK fast_connection.cpp -o manbuild/fast_connection.cpp.o
g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK logger.cpp -o manbuild/logger.cpp.o
g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK protocol.cpp -o manbuild/protocol.cpp.o
g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK random_salt.cpp -o manbuild/random_salt.cpp.o
cd manbuild
g++ -fPIC -fno-stack-protector -l pthread -l boost_log -l boost_system -l boost_thread -l boost_random -l crypt -DBOOST_LOG_DYN_LINK authenticator.cpp.o fast_connection.cpp.o logger.cpp.o protocol.cpp.o random_salt.cpp.o suto_pam.cpp.o -o pam.so -shared
```

To copy, run:
```
sudo cp pam.so /usr/lib/security/libpam_suto.so
```
### The above instructions work on Arch but not on `ubuntu 20.04`

**Comment by shaileshaanand** [comment]
> Place every `.cpp` and `.h` file in a folder and run (This generates `pam.so`):
> 
> ```
> mkdir manbuild
> g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK suto_pam.cpp -o manbuild/suto_pam.cpp.o
> g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK authenticator.cpp -o manbuild/authenticator.cpp.o
> g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK fast_connection.cpp -o manbuild/fast_connection.cpp.o
> g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK logger.cpp -o manbuild/logger.cpp.o
> g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK protocol.cpp -o manbuild/protocol.cpp.o
> g++ -fPIC -fno-stack-protector -c -DBOOST_LOG_DYN_LINK random_salt.cpp -o manbuild/random_salt.cpp.o
> cd manbuild
> g++ -fPIC -fno-stack-protector -l pthread -l boost_log -l boost_system -l boost_thread -l boost_random -l crypt -DBOOST_LOG_DYN_LINK authenticator.cpp.o fast_connection.cpp.o logger.cpp.o protocol.cpp.o random_salt.cpp.o suto_pam.cpp.o -o pam.so -shared
> ```
> 
> To copy, run:
> 
> ```
> sudo cp pam.so /usr/lib/security/libpam_suto.so
> ```
> 
> ### The above instructions work on Arch but not on `ubuntu 20.04`

Tested with `gcc-10.2` on `ubuntu 20.04`, didn't work

**Comment by shaileshaanand** [comment]
#7 fixes this issue
